import test from 'node:test';
import assert from 'node:assert/strict';
import {World,distance} from '../src/engine.mjs';
import {NODES,RULES,EQUIPMENT} from '../src/content.mjs';
import {countItem} from '../src/inventory.mjs';
function camp(){const w=new World(402);const p=w.addPlayer('host','Jun');w.start();return {w,p};}
function qty(container,itemId){return countItem(container,itemId);}
function setPack(w,p,counts){w.clearPack(p);for(const [itemId,count] of Object.entries(counts))w.stock(p.inventory,itemId,count);}
function setStore(w,store,counts){for(const [itemId,count] of Object.entries(counts))w.stock(store,itemId,count);}
function tool(p,itemId){return [...p.inventory.slots, ...Object.values(p.equipment)].find(stack=>stack?.itemId===itemId);}
function act(w,p,cmd){p.cooldown=0;w.action(p.id,cmd);}
function tick(w,n){for(let i=0;i<n;i++)w.tick();}
test('seeded world guarantees starter materials and restores depleted nodes',()=>{const {w,p}=camp();assert.deepEqual(w.nodes,new World(402).nodes);const n=w.nodes.find(n=>n.type==='grass');p.x=n.x;p.z=n.z+1;act(w,p,{type:'interact',target:n.id});assert.equal(qty(p.inventory,'fiber'),7);assert.ok(n.ready>0);const copy=World.restore(JSON.parse(JSON.stringify(w.snapshot())));assert.deepEqual(copy.snapshot(),w.snapshot());assert.equal(copy.nodes.find(x=>x.id===n.id).ready,n.ready);});
test('crafting consumes only available supplies, uses nearby shared chests, and has station gates',()=>{const {w,p}=camp();w.clearPack(p);const chest=w.structure('chest',p.x+1,p.z);setStore(w,chest.store,{wood:8,stone:5,fiber:6});w.buildings.push(chest);act(w,p,{type:'craft',recipe:'axe'});assert.equal(tool(p,'axe').durability,EQUIPMENT.axe.durability);assert.equal(p.equipment.chop,null);assert.equal(qty(chest.store,'wood'),6);act(w,p,{type:'craft',recipe:'armor'});assert.equal(tool(p,'armor'),undefined);w.buildings.push(w.structure('bench',p.x+2,p.z));act(w,p,{type:'craft',recipe:'armor'});assert.equal(tool(p,'armor').durability,110);assert.equal(p.equipment.body,null);assert.equal(qty(chest.store,'fiber'),1);act(w,p,{type:'craft',recipe:'sword'});assert.equal(tool(p,'sword'),undefined);});
test('two players cannot spend the same shared materials',()=>{const {w,p}=camp();w.clearPack(p);const q=w.addPlayer('guest');w.clearPack(q);const chest=w.structure('chest',3,2);setStore(w,chest.store,{wood:2,stone:2});w.buildings.push(chest);act(w,p,{type:'craft',recipe:'axe'});act(w,q,{type:'craft',recipe:'axe'});assert.equal(tool(p,'axe').durability,70);assert.equal(tool(q,'axe'),undefined);assert.equal(qty(chest.store,'wood'),0);assert.equal(qty(chest.store,'stone'),0);});
test('build rejects remote placement, overlap, missing costs and inherited recipe names',()=>{const {w,p}=camp();setPack(w,p,{wood:20,stone:20});let count=w.buildings.length;act(w,p,{type:'build',recipe:'wall',x:40,z:40});assert.equal(w.buildings.length,count);act(w,p,{type:'build',recipe:'wall',x:0,z:0});assert.equal(w.buildings.length,count);act(w,p,{type:'build',recipe:'wall',x:p.x,z:p.z});assert.equal(w.buildings.length,count);for(const recipe of ['__proto__','constructor','toString']){assert.doesNotThrow(()=>act(w,p,{type:'craft',recipe}));assert.doesNotThrow(()=>act(w,p,{type:'build',recipe,x:2,z:5}));}act(w,p,{type:'build',recipe:'wall',x:0,z:4});assert.equal(w.buildings.length,count+1);assert.equal(qty(p.inventory,'wood'),17);});
test('equipment changes harvesting rate and is required for iron and graves',()=>{const {w,p}=camp();const n=w.nodes.find(n=>n.type==='ore');p.x=n.x;p.z=n.z+1;act(w,p,{type:'interact',target:n.id});assert.equal(n.hits,NODES.ore.hits);w.grantEquipped(p,'pick',1);act(w,p,{type:'interact',target:n.id});assert.equal(n.hits,4);assert.equal(p.equipment.mine,null);act(w,p,{type:'interact',target:n.id});assert.equal(n.hits,4);});
test('bounded normalized input, input expiry and collisions prevent teleporting',()=>{const {w,p}=camp();p.x=0;p.z=2;w.input(p.id,{x:0,z:-999});tick(w,5);assert.ok(p.z>=1.3);w.input(p.id,{x:NaN,z:0});const x=p.x;tick(w,30);assert.ok(Number.isFinite(p.x));assert.equal(p.x,x);w.input(p.id,{x:1,z:1});const start={x:p.x,z:p.z};w.tick();assert.ok(distance(start,p)<=RULES.speed*RULES.tick+.001);});
test('darkness hurts outside light; hunger is independent of darkness',()=>{const {w,p}=camp();w.time=190;w.nextSpawn=999;p.x=30;p.z=30;p.courage=0;p.hunger=0;p.hp=100;tick(w,20);assert.ok(p.hp<94);p.hunger=90;p.courage=50;p.x=2;p.z=0;w.buildings[0].fuel=120;const hp=p.hp;tick(w,20);assert.equal(p.hp,hp);assert.ok(p.courage>50);});
test('cooking needs a burning fire; farming grows then yields seeds for replanting',()=>{const {w,p}=camp();p.x=2;p.z=0;setPack(w,p,{pumpkin:2,seed:2});act(w,p,{type:'craft',recipe:'roast'});assert.equal(qty(p.inventory,'roast'),1);w.buildings[0].fuel=0;act(w,p,{type:'craft',recipe:'roast'});assert.equal(qty(p.inventory,'roast'),1);const farm=w.structure('farm',2,1);w.buildings.push(farm);act(w,p,{type:'interact',target:farm.id});assert.ok(farm.planted);farm.growth=100;act(w,p,{type:'interact',target:farm.id});assert.equal(qty(p.inventory,'pumpkin'),4);assert.equal(qty(p.inventory,'seed'),3);assert.equal(farm.planted,false);});
test('dodging cancels into invulnerability while attacks have cooldown and wear',()=>{const {w,p}=camp();w.spawnEnemy('crawler',p.x+1,p.z);w.grantEquipped(p,'spear',2);act(w,p,{type:'attack'});assert.equal(w.enemies[0].hp,24);assert.equal(p.equipment.weapon.durability,1);assert.equal(p.equipment.weapon.itemId,'spear');w.action(p.id,{type:'attack'});assert.equal(w.enemies[0].hp,24);w.action(p.id,{type:'dash'});assert.ok(p.dash>0);w.hurt(p,20);assert.equal(p.hp,100);});
test('teammate revival, charm and total-party defeat work without resetting the world',()=>{const {w,p}=camp(),q=w.addPlayer('guest');p.x=q.x+1;p.z=q.z;q.hp=0;q.down=40;for(let i=0;i<6;i++)act(w,p,{type:'interact',target:q.id});assert.equal(q.down,0);assert.equal(w.stats.revives,1);w.hurt(q,999);act(w,q,{type:'interact'});assert.equal(q.down,0);assert.equal(q.charm,0);p.charm=0;w.hurt(p,999);w.hurt(q,999);tick(w,130);assert.equal(w.status,'defeat');});
test('traps and wards damage mobs; building damage and repairs use real costs',()=>{const {w,p}=camp();const trap=w.structure('trap',5,5);w.buildings.push(trap);w.spawnEnemy('brute',5,5);w.tick();assert.equal(trap.charges,2);assert.ok(w.enemies[0].hp<160);const wall=w.structure('wall',p.x+1,p.z);wall.hp=40;w.buildings.push(wall);setPack(w,p,{wood:1});act(w,p,{type:'repair',target:wall.id});assert.equal(wall.hp,130);assert.equal(qty(p.inventory,'wood'),0);act(w,p,{type:'repair',target:wall.id});assert.equal(wall.hp,130);});
test('fifth night spawns one boss; slaying it wins at dawn, and hearth loss defeats',()=>{const {w,p}=camp();w.time=RULES.cycle*4+179.98;p.x=0;p.z=3;w.tick();assert.equal(w.enemies.filter(e=>e.type==='king').length,1);w.spawnWave();assert.equal(w.enemies.filter(e=>e.type==='king').length,1);w.enemies.find(e=>e.type==='king').hp=0;w.tick();assert.ok(w.bossSlain);w.time=RULES.cycle*5-.02;w.tick();assert.equal(w.status,'victory');const other=camp();other.w.buildings[0].hp=0;other.w.tick();assert.equal(other.w.status,'defeat');});
test('disconnects stop inputs and reconnect slots are bounded',()=>{const {w,p}=camp();w.addPlayer('two');w.addPlayer('three');w.addPlayer('four');assert.equal(w.addPlayer('five'),null);w.input('two',{x:1,z:0});w.leave('two');assert.equal(w.inputs.has('two'),false);assert.ok(w.addPlayer('five'));assert.equal(w.players.length,4);assert.equal(w.players.filter(p=>p.online).length,4);});
