import test from 'node:test';
import assert from 'node:assert/strict';
import {World,distance} from '../src/engine.mjs';
import {NODES,RULES,EQUIPMENT} from '../src/content.mjs';
import {countItem} from '../src/inventory.mjs';
function camp(){const w=new World(402);const p=w.addPlayer('host','Jun');w.start();w.ambient=false;w.enemies=[];p.regions=['meadow','woods','graveyard','mire','crags','barrow'];return {w,p};}
function qty(container,itemId){return countItem(container,itemId);}
function setPack(w,p,counts){w.clearPack(p);for(const [itemId,count] of Object.entries(counts))w.stock(p.inventory,itemId,count);}
function setStore(w,store,counts){for(const [itemId,count] of Object.entries(counts))w.stock(store,itemId,count);}
function tool(p,itemId){return [...p.inventory.slots, ...Object.values(p.equipment)].find(stack=>stack?.itemId===itemId);}
function act(w,p,cmd){p.cooldown=0;return w.action(p.id,cmd);}
function tick(w,n){for(let i=0;i<n;i++)w.tick();}
function hold(w,p,target,seconds){
  let left=seconds;
  while(left>1e-8){
    const dt=Math.min(RULES.tick, left);
    w.input(p.id,{x:0,z:0,act:true,attack:false,target});
    w.tick(dt);
    left-=dt;
  }
}
test('seeded world guarantees starter materials and restores depleted nodes',()=>{const {w,p}=camp();assert.deepEqual(w.nodes,new World(402).nodes);const n=w.nodes.find(n=>n.type==='grass');p.x=n.x;p.z=n.z+1;const fiber=qty(p.inventory,'fiber');for(let i=0;i<8;i++)act(w,p,{type:'interact',target:n.id});assert.equal(qty(p.inventory,'fiber'),fiber);assert.equal(n.ready,0);hold(w,p,n.id,0.85);assert.equal(n.ready,0);assert.equal(qty(p.inventory,'fiber'),fiber);hold(w,p,n.id,0.1);assert.equal(qty(p.inventory,'fiber'),fiber+4);assert.ok(n.ready>0);assert.equal(n.hits,0);const copy=World.restore(JSON.parse(JSON.stringify(w.snapshot())));assert.deepEqual(copy.snapshot(),w.snapshot());assert.equal(copy.nodes.find(x=>x.id===n.id).ready,n.ready);});
test('crafting consumes only available supplies, uses nearby shared chests, and has station gates',()=>{const {w,p}=camp();w.clearPack(p);const chest=w.structure('chest',p.x+1,p.z);setStore(w,chest.store,{wood:8,stone:5,fiber:6});const bench=w.structure('bench',p.x+2,p.z);w.buildings.push(chest,bench);assert.equal(act(w,p,{type:'craft',recipe:'axe'}).code,'stationRequired');assert.equal(qty(chest.store,'wood'),8);assert.equal(act(w,p,{type:'craft',recipe:'axe',stationId:bench.id}).ok,true);assert.equal(tool(p,'axe').durability,EQUIPMENT.axe.durability);assert.equal(p.equipment.chop,null);assert.equal(qty(chest.store,'wood'),6);assert.equal(act(w,p,{type:'craft',recipe:'armor'}).code,'stationRequired');assert.equal(tool(p,'armor'),undefined);assert.equal(qty(chest.store,'fiber'),6);assert.equal(act(w,p,{type:'craft',recipe:'armor',stationId:bench.id}).ok,true);assert.equal(tool(p,'armor').durability,110);assert.equal(p.equipment.body,null);assert.equal(qty(chest.store,'fiber'),1);assert.equal(act(w,p,{type:'craft',recipe:'sword',stationId:bench.id}).ok,false);assert.equal(tool(p,'sword'),undefined);});
test('two players cannot spend the same shared materials',()=>{const {w,p}=camp();w.clearPack(p);const q=w.addPlayer('guest');w.clearPack(q);const chest=w.structure('chest',3,2);setStore(w,chest.store,{wood:2,stone:2});const bench=w.structure('bench',2.4,2.4);w.buildings.push(chest,bench);assert.equal(act(w,p,{type:'craft',recipe:'axe',stationId:bench.id}).ok,true);assert.equal(act(w,q,{type:'craft',recipe:'axe',stationId:bench.id}).ok,false);assert.equal(tool(p,'axe').durability,70);assert.equal(tool(q,'axe'),undefined);assert.equal(qty(chest.store,'wood'),0);assert.equal(qty(chest.store,'stone'),0);});
test('build rejects remote placement, overlap, missing costs and inherited recipe names',()=>{const {w,p}=camp();setPack(w,p,{wood:20,stone:20});let count=w.buildings.length;act(w,p,{type:'build',recipe:'wall',x:40,z:40});assert.equal(w.buildings.length,count);act(w,p,{type:'build',recipe:'wall',x:0,z:0});assert.equal(w.buildings.length,count);act(w,p,{type:'build',recipe:'wall',x:p.x,z:p.z});assert.equal(w.buildings.length,count);for(const recipe of ['__proto__','constructor','toString']){assert.doesNotThrow(()=>act(w,p,{type:'craft',recipe}));assert.doesNotThrow(()=>act(w,p,{type:'build',recipe,x:2,z:5}));}act(w,p,{type:'build',recipe:'wall',x:0,z:4});assert.equal(w.buildings.length,count+1);assert.equal(qty(p.inventory,'wood'),17);});
test('equipment changes harvesting rate and is required for iron and graves',()=>{const {w,p}=camp();const n=w.nodes.find(n=>n.type==='ore');p.x=n.x;p.z=n.z+1;hold(w,p,n.id,1);assert.equal(n.hits,NODES.ore.hits);assert.equal(n.ready,0);w.grantEquipped(p,'pick',1);hold(w,p,n.id,1);assert.equal(p.equipment.mine,null);assert.equal(n.ready,0);assert.equal(n.hits,NODES.ore.hits);hold(w,p,n.id,3);assert.equal(n.ready,0);assert.equal(w.drops.some(d=>d.stack.itemId==='ore'),false);});
test('bounded normalized input, input expiry and collisions prevent teleporting',()=>{const {w,p}=camp();p.x=0;p.z=2;w.input(p.id,{x:0,z:-999});tick(w,5);assert.ok(p.z>=1.3);w.input(p.id,{x:NaN,z:0});const x=p.x;tick(w,30);assert.ok(Number.isFinite(p.x));assert.equal(p.x,x);w.input(p.id,{x:1,z:1});const start={x:p.x,z:p.z};w.tick();assert.ok(distance(start,p)<=RULES.speed*RULES.tick+.001);});
test('darkness hurts outside light; hunger is independent of darkness',()=>{const {w,p}=camp();w.time=RULES.day+RULES.dusk+10;w.nextSpawn=w.time+RULES.night;p.x=30;p.z=30;p.courage=0;p.hunger=0;p.hp=100;tick(w,20);assert.ok(p.hp<94);p.hunger=90;p.courage=50;p.x=2;p.z=0;w.buildings[0].fuel=120;const hp=p.hp;tick(w,20);assert.equal(p.hp,hp);assert.ok(p.courage>50);});
test('cooking needs a burning fire; farming grows then yields seeds for replanting',()=>{const {w,p}=camp();p.x=2;p.z=0;setPack(w,p,{pumpkin:2,seed:2});const heart=w.buildings[0];assert.equal(act(w,p,{type:'craft',recipe:'roast'}).code,'stationRequired');assert.equal(qty(p.inventory,'roast'),0);assert.equal(act(w,p,{type:'craft',recipe:'roast',stationId:heart.id}).ok,true);assert.equal(qty(p.inventory,'roast'),1);heart.fuel=0;assert.equal(act(w,p,{type:'craft',recipe:'roast',stationId:heart.id}).code,'missingFuel');assert.equal(qty(p.inventory,'roast'),1);heart.fuel=40;assert.equal(act(w,p,{type:'craft',recipe:'roast'}).ok,false);assert.equal(qty(p.inventory,'roast'),1);const farm=w.structure('farm',2,1);w.buildings.push(farm);act(w,p,{type:'interact',target:farm.id});assert.ok(farm.planted);farm.growth=100;act(w,p,{type:'interact',target:farm.id});assert.equal(qty(p.inventory,'pumpkin'),4);assert.equal(qty(p.inventory,'seed'),3);assert.equal(farm.planted,false);});
test('dodging cancels into invulnerability while attacks have cooldown and wear',()=>{const {w,p}=camp();w.spawnEnemy('crawler',p.x+1,p.z);w.grantEquipped(p,'spear',2);act(w,p,{type:'attack'});assert.equal(w.enemies[0].hp,48-EQUIPMENT.spear.damage);assert.equal(p.equipment.weapon.durability,1);assert.equal(p.equipment.weapon.itemId,'spear');w.action(p.id,{type:'attack'});assert.equal(w.enemies[0].hp,48-EQUIPMENT.spear.damage);w.action(p.id,{type:'dash'});assert.ok(p.dash>0);w.hurt(p,20);assert.equal(p.hp,100);});
test('a hit writes a damage number on the player',()=>{const {w,p}=camp();p.hp=100;w.hurt(p,17);const ev=w.events.filter(e=>e.type==='hurt').at(-1);assert.equal(ev.text,'−17');assert.equal(ev.x,p.x);assert.equal(ev.z,p.z);assert.equal(ev.player,p.id);});
test('teammate revival, charm and total-party defeat work without resetting the world',()=>{const {w,p}=camp(),q=w.addPlayer('guest');p.x=q.x+1;p.z=q.z;q.hp=0;q.down=40;for(let i=0;i<6;i++)act(w,p,{type:'interact',target:q.id});assert.equal(q.down,40);assert.equal(w.stats.revives,0);hold(w,p,q.id,2.9);assert.ok(q.down>0);assert.equal(w.stats.revives,0);hold(w,p,q.id,0.15);assert.equal(q.down,0);assert.equal(q.hp,50);assert.equal(w.stats.revives,1);w.hurt(q,999);act(w,q,{type:'interact'});assert.equal(q.down,0);assert.equal(q.charm,0);p.charm=0;w.hurt(p,999);w.hurt(q,999);tick(w,130);assert.equal(w.status,'defeat');});
test('traps and wards damage mobs; building damage and repairs use real costs',()=>{const {w,p}=camp();const trap=w.structure('trap',5,5);w.buildings.push(trap);w.spawnEnemy('brute',5,5);w.tick();assert.equal(trap.charges,2);assert.ok(w.enemies[0].hp<160);const wall=w.structure('wall',p.x+1,p.z);wall.hp=40;w.buildings.push(wall);setPack(w,p,{wood:1});act(w,p,{type:'repair',target:wall.id});assert.equal(wall.hp,130);assert.equal(qty(p.inventory,'wood'),0);act(w,p,{type:'repair',target:wall.id});assert.equal(wall.hp,130);});
test('fifth night spawns one boss; slaying it keeps the endless expedition going, and hearth loss defeats',()=>{const {w,p}=camp();w.time=RULES.cycle*4+RULES.day+RULES.dusk-0.02;p.x=0;p.z=3;w.tick();assert.equal(w.enemies.filter(e=>e.type==='king').length,1);w.spawnWave();assert.equal(w.enemies.filter(e=>e.type==='king').length,1);w.enemies.find(e=>e.type==='king').hp=0;w.tick();assert.ok(w.bossSlain);w.time=RULES.cycle*5-.02;w.tick();assert.equal(w.status,'playing');assert.equal(RULES.cycle*RULES.finalNight,1550);const other=camp();other.w.buildings[0].hp=0;other.w.tick();assert.equal(other.w.status,'defeat');});
test('disconnects stop inputs and reconnect slots are bounded',()=>{const {w,p}=camp();w.addPlayer('two');w.addPlayer('three');w.addPlayer('four');assert.equal(w.addPlayer('five'),null);w.input('two',{x:1,z:0});w.leave('two');assert.equal(w.inputs.has('two'),false);assert.ok(w.addPlayer('five'));assert.equal(w.players.length,4);assert.equal(w.players.filter(p=>p.online).length,4);});
